In [1]:
import torch

In [2]:
torch.ones(3)

tensor([1., 1., 1.])

In [21]:
x = torch.tensor([1,2,3.], requires_grad=True)

In [22]:
x

tensor([1., 2., 3.], requires_grad=True)

In [30]:
z1 = (x ** 2).sum() # x**2 -> 2 * x
z2 = (x ** 3).sum() # x**3 -> 3 * x**2

In [32]:
z1.backward()

In [33]:
x.grad

tensor([ 7., 20., 39.])

In [35]:
x.grad.zero_()

tensor([0., 0., 0.])

In [36]:
x.grad

tensor([0., 0., 0.])

In [37]:
z2.backward()

In [38]:
x.grad # [3, 12, 27]

tensor([ 3., 12., 27.])

In [28]:
x

tensor([1., 2., 3.], requires_grad=True)

In [13]:
y.detach().numpy()

array([1., 4., 9.], dtype=float32)

градиентный алгоритм минимизации функции (псевдокод)

In [ ]:
def f(x):
    ...
    ...
    ...
    return z

alpha = 0.001
x = torch.randn(..., requires_grad=True)
for it in range(1000):
    z = f(x)
    z.backward()
    x = x - alpha * x.grad
    x.grad.zero_()

In [26]:
y.backward(torch.tensor([1,1.,1]))

In [27]:
z

tensor(14., grad_fn=<SumBackward0>)

In [28]:
z.item()

14.0

In [32]:
y.detach().numpy()

array([1., 4., 9.], dtype=float32)

In [33]:
y.numpy()

RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.

In [18]:
x = torch.tensor([1, 2, 3.], requires_grad=True)
z1 = (x**2).sum()
z2 = (x**3).sum()

In [19]:
z1.backward()

In [20]:
x.grad

tensor([2., 4., 6.])

In [21]:
x.grad.zero_()
z2.backward()

In [22]:
x.grad

tensor([ 3., 12., 27.])

In [ ]:
x**2 -> 2 * x
x**3 -> 3 * x**2 == [3, 12, 27]